[package]
name = "webserver"
version = "1.1.0"
edition = "2021"
repository = "https://github.com/Lut99/webserver-rs"
description = "An `axum-`based webserver that can be used to do simple static website hosting."


[dependencies]
axum = "0.8.1"
axum-extra = { version = "0.10.0", features = ["async-read-body"] }
axum-macros = { version = "0.5.0", optional = true }
base64ct = { version = "1.6.0", features = ["std"] }
clap = { version = "4.5.31", features = ["derive"] }
error-trace = "4.0.0"
humanlog = { git = "https://github.com/Lut99/humanlog-rs" }
hyper = "1.6.0"
hyper-util = "0.1.10"
log = "0.4.26"
serde = { version = "1.0.218", features = ["derive"] }
serde_yml = "0.0.12"
thiserror = "2.0.11"
tokio = { version = "1.43.0", default-features = false, features = [
    "fs",
    "macros",
    "rt",
    "rt-multi-thread",
    "signal",
] }
tower-service = "0.3.3"


[features]
default = []

axum-debug = ["dep:axum-macros"]
