services:
  ##################
  ## WEBSERVER-RS ##
  ##################

  # The Rust webserver
  webserver:
    build:
      dockerfile: ./Dockerfile
      context: .
      target: release
    container_name: webserver
    user: webserver
    restart: always
    command:
    - --address
    - 0.0.0.0:42080
    ports:
    - ${PORT:-42080}:42080
    volumes:
    - ${CONFIG:-./config.yml}:/config.yml
    - ${WWW_DIR:-./www}:/www

networks:
  webserver:
    driver: default
